spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: -1
            max-request-size: -1

server:
  port: 10000

management.server.port: 10100
management.endpoint.health.group.custom.show-components: always
management.endpoint.health.group.custom.show-details: always
management.endpoints.web.exposure.include: health,beans,conditions,auditevents,env,flyway,heapdumps,info,liquibase,logfile,loggers,metrics,prometheus,scheduledtasks,sessions,threaddump

springdoc:
    use-management-port: true